# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://constellation.rs" # the base hostname & protocol for your site, e.g. http://example.com

title: The Constellation Project
author: constellation-rs
email: core@constellation.rs
description: >- # this means to ignore newlines until "baseurl:"
  The home of The Constellation Project to make Rust the cutting edge of distributed computing.
twitter_username: constellation-rs
github_username:  constellation-rs
# linkedin_username: constellation-rs
# rss: rss

# data:
#   authors:
#     constellation-rs:
#       twitter: constellation-rs

show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - chat.md
  - contributing.md
  - thanks.md
  - blog.md
  - constellation.md
  - constellation_tutorial.md
  - constellation_help.md
  - constellation_features.md
  - https://github.com/constellation-rs/constellation,GitHub,code
  - https://docs.rs/constellation-rs,Documentation,menu_book
  - amadeus.md
  - amadeus_tutorial.md
  - amadeus_help.md
  - amadeus_features.md
  - https://github.com/constellation-rs/amadeus,GitHub,code
  - https://docs.rs/amadeus,Documentation,menu_book

permalink: /:year/:month/:day/:title

social:
  links:
    - https://twitter.com/constellation-rs
    # - https://www.facebook.com/alec2
    # - https://www.linkedin.com/in/constellation-rs
    # - https://plus.google.com/+BenBalter
    - https://github.com/constellation-rs
    # - https://keybase.io/mocatta

twitter:
  username: constellation-rs
  card: summary

google_analytics: UA-126485616-2

exclude:
  # Default
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Custom
  - README.md
